image: Visual Studio 2017

platform:
  - x64

environment:
  NODE_OPTIONS: --max_old_space_size=16000

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 16 x64
  - yarn

build_script:
  - yarn electron:build

test: off

artifacts:
  - path: 'dist_electron\**\*.exe'
    name: MyApp

deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: s7kJZxQutpKHRRZ1p3jA0zqEgiZXpKWRC2rJj8wkYDm97VJ2hizyxtJKtlDp8dLW # your encrypted token from GitHub
  artifact: /.*\.exe/            # upload all exe files to release assets
  draft: true
  force_update: true
  on:
    APPVEYOR_REPO_TAG: true        # deploy on tag push only
